name: Test

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

env:
  total-runners: 5

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@pablotoro19'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run test
